local M = {
    common = {
        ["pause"] = 0xF000,
        ["resume"] = 0xF001
    },
    player = {
        ["sync"] = 0xF100,
        ["load"] = 0xF101,
        ["login"] = 0xF102,
        ["fetchFields"] = 0xF103,
        ["change"] = 0xF104
    },
    payments = {
        ["purchase"] = 0xF200,
        ["error:purchase"] = 0xF201,
        ["consume"] = 0xF202,
        ["error:consume"] = 0xF203,
        ["fetchProducts"] = 0xF204,
        ["error:fetchProducts"] = 0xF205,
        ["subscribe"] = 0xF206,
        ["error:subscribe"] = 0xF207,
        ["unsubscribe"] = 0xF208,
        ["error:unsubscribe"] = 0xF209
    },
    channels = {
        ["createChannel"] = 0xF300,
        ["error:createChannel"] = 0xF301,
        ["updateChannel"] = 0xF302,
        ["error:updateChannel"] = 0xF303,
        ["event:updateChannel"] = 0xF304,
        ["deleteChannel"] = 0xF305,
        ["error:deleteChannel"] = 0xF306,
        ["event:deleteChannel"] = 0xF307,
        ["fetchChannel"] = 0xF308,
        ["error:fetchChannel"] = 0xF309,
        ["fetchChannels"] = 0xF30A,
        ["error:fetchChannels"] = 0xF30B,
        ["fetchMoreChannels"] = 0xF30C,
        ["error:fetchMoreChannels"] = 0xF30D,

        ["join"] = 0xF30E,
        ["error:join"] = 0xF30F,
        ["event:join"] = 0xF310,
        ["event:joinRequest"] = 0xF311,
        ["cancelJoin"] = 0xF312,
        ["error:cancelJoin"] = 0xF313,
        ["event:cancelJoin"] = 0xF314,
        ["leave"] = 0xF315,
        ["error:leave"] = 0xF316,
        ["event:leave"] = 0xF317,
        ["kick"] = 0xF318,
        ["error:kick"] = 0xF319,
        ["fetchMembers"] = 0xF31A,
        ["error:fetchMembers"] = 0xF31B,
        ["fetchMoreMembers"] = 0xF31C,
        ["error:fetchMoreMembers"] = 0xF31D,
        ["mute"] = 0xF31E,
        ["error:mute"] = 0xF31F,
        ["event:mute"] = 0xF320,
        ["unmute"] = 0xF321,
        ["error:unmute"] = 0xF322,
        ["event:unmute"] = 0xF323,

        ["sendInvite"] = 0xF324,
        ["error:sendInvite"] = 0xF325,
        ["event:invite"] = 0xF326,
        ["cancelInvite"] = 0xF327,
        ["error:cancelInvite"] = 0xF328,
        ["event:cancelInvite"] = 0xF329,
        ["acceptInvite"] = 0xF32A,
        ["error:acceptInvite"] = 0xF32B,
        ["rejectInvite"] = 0xF32C,
        ["error:rejectInvite"] = 0xF32D,
        ["event:rejectInvite"] = 0xF32E,
        ["fetchInvites"] = 0xF32F,
        ["error:fetchInvites"] = 0xF330,
        ["fetchMoreInvites"] = 0xF331,
        ["error:fetchMoreInvites"] = 0xF332,
        ["fetchChannelInvites"] = 0xF333,
        ["error:fetchChannelInvites"] = 0xF334,
        ["fetchMoreChannelInvites"] = 0xF335,
        ["error:fetchMoreChannelInvites"] = 0xF336,
        ["fetchSentInvites"] = 0xF337,
        ["error:fetchSentInvites"] = 0xF338,
        ["fetchMoreSentInvites"] = 0xF339,
        ["error:fetchMoreSentInvites"] = 0xF33A,

        ["acceptJoinRequest"] = 0xF33B,
        ["error:acceptJoinRequest"] = 0xF33C,
        ["rejectJoinRequest"] = 0xF33D,
        ["error:rejectJoinRequest"] = 0xF33E,
        ["event:rejectJoinRequest"] = 0xF33F,
        ["fetchJoinRequests"] = 0xF340,
        ["error:fetchJoinRequests"] = 0xF341,
        ["fetchMoreJoinRequests"] = 0xF342,
        ["error:fetchMoreJoinRequests"] = 0xF343,
        ["fetchSentJoinRequests"] = 0xF344,
        ["error:fetchSentJoinRequests"] = 0xF345,
        ["fetchMoreSentJoinRequests"] = 0xF346,
        ["error:fetchMoreSentJoinRequests"] = 0xF347,

        ["sendMessage"] = 0xF348,
        ["error:sendMessage"] = 0xF349,
        ["event:message"] = 0xF34A,
        ["editMessage"] = 0xF34B,
        ["error:editMessage"] = 0xF34C,
        ["event:editMessage"] = 0xF34D,
        ["deleteMessage"] = 0xF34E,
        ["error:deleteMessage"] = 0xF34F,
        ["event:deleteMessage"] = 0xF350,
        ["fetchMessages"] = 0xF351,
        ["error:fetchMessages"] = 0xF352,
        ["fetchMoreMessages"] = 0xF351,
        ["error:fetchMoreMessages"] = 0xF352
    },
    ads = {
        ["start"] = 0xF400,
        ["close"] = 0xF401,
        ["fullscreen:start"] = 0xF402,
        ["fullscreen:close"] = 0xF403,
        ["preloader:start"] = 0xF404,
        ["preloader:close"] = 0xF405,
        ["rewarded:start"] = 0xF406,
        ["rewarded:close"] = 0xF407,
        ["rewarded:reward"] = 0xF408,
        ["sticky:start"] = 0xF409,
        ["sticky:render"] = 0xF40A,
        ["sticky:refresh"] = 0xF40B,
        ["sticky:close"] = 0xF40C
    },
    achievements = {
        ["unlock"] = 0xF500,
        ["error:unlock"] = 0xF501,
        ["progress"] = 0xF502,
        ["error:progress"] = 0xF503,
        ["open"] = 0xF504,
        ["close"] = 0xF505,
        ["fetch"] = 0xF506,
        ["error:fetch"] = 0xF507
    },
    variables = {
        ["fetch"] = 0xF600,
        ["error:fetch"] = 0xF601
    },
    gamesCollections = {
        ["open"] = 0xF700,
        ["close"] = 0xF701,
        ["fetch"] = 0xF702,
        ["error:fetch"] = 0xF703
    },
    images = {
        ["upload"] = 0xF800,
        ["error:upload"] = 0xF801,
        ["choose"] = 0xF802,
        ["error:choose"] = 0xF803,
        ["fetch"] = 0xF804,
        ["error:fetch"] = 0xF805,
        ["fetchMore"] = 0xF806,
        ["error:fetchMore"] = 0xF807
    },
    files = {
        ["upload"] = 0xF900,
        ["error:upload"] = 0xF901,
        ["loadContent"] = 0xF902,
        ["error:loadContent"] = 0xF903,
        ["choose"] = 0xF904,
        ["error:choose"] = 0xF905,
        ["fetch"] = 0xF906,
        ["error:fetch"] = 0xF907,
        ["fetchMore"] = 0xF908,
        ["error:fetchMore"] = 0xF909
    },
    documents = {
        ["open"] = 0xFA00,
        ["close"] = 0xFA01,
        ["fetch"] = 0xFA02,
        ["error:fetch"] = 0xFA03
    },
    fullscreen = {
        ["open"] = 0xFB00,
        ["close"] = 0xFB01,
        ["change"] = 0xFB02
    }
}

return M